name: conduit_open_api
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 1.0.0-b1
homepage: https://github.com/conduit-dart/open-api-dart
authors: 
  stable|kernel <jobs@stablekernel.com>
  bsutton@noojee.com.au


environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  conduit_codable: ^1.0.0-0
  meta: ^1.1.5

dev_dependencies:
  dcli: ^0.51.0
  lint: ^1.5.3
  test: ^1.3.0
  

dependency_overrides:
  # conduit_codable: 
  #   path: ../conduit-codable

