name: conduit_open_api
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 1.0.0-b1
homepage: https://github.com/conduit-dart/open-api-dart
authors: 
  stable|kernel <jobs@stablekernel.com>
  bsutton@noojee.com.au


environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.5
  conduit_codable: ^1.0.0-0

dev_dependencies:
  test: ^1.3.0

override_dependencies:
  path: ../conduit_codable

